### PR TITLE
Add dynamic background image

### PR DESCRIPTION
**Pull request by lyneca**
This PR makes the background image change when day turns to night.

### CODE REVIEW

**Comment by lyneca** [comment]
I also adjusted the background image to cover the available space, and moved a few things around

**Review by Makosai — CHANGES_REQUESTED** [review]
A few things to be done before the merger:
- Move twitter icon from the bottom to the navbar.
- Delete the footer entirely.
- Reference to the image with absolute paths on line 34 and 38 in the clock.js files (put a / before assets so this works even if index.html was relocated).

I like the change. The navbar looks nice.

**Comment by lyneca** [comment]
Thanks, I'll do that now

**Comment by lyneca** [comment]
Putting a `/` at the front of those lines in assets stops those images from loading, and in other places in your site you've just got `assets/whatever` (without the slash).

**Comment by Makosai** [comment]
Yeah, I didn't think about how github.io was using a folder as the directory. So the "/" equivalent would go 1 directory up. An easy fix would be to do "/Plains-of-Eidolon-Clock/assets/...". I'll sort something out. Merging your pull request. Thanks for the changes. I'll also work on getting the twitter icon to work on multiple sizes.

**Pull request merged**
